// <auto-generated />
using DAL.DbContextBuilder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(TodoListDbContext))]
    [Migration("20260515150157_SeedMigration")]
    partial class SeedMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TodoListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TodoListId");

                    b.ToTable("Todo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Name = "Bread",
                            TodoListId = 1
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Description = "Fat",
                            Name = "Milk",
                            TodoListId = 1
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Description = "San-Sebastian cake",
                            Name = "Cake",
                            TodoListId = 1
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Description = "Send weekly status report",
                            Name = "Send report",
                            TodoListId = 2
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Description = "Check backend changes",
                            Name = "Review pull request",
                            TodoListId = 2
                        },
                        new
                        {
                            Id = 6,
                            Active = false,
                            Name = "Update documentation",
                            TodoListId = 2
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            Description = "Practice migrations and relationships",
                            Name = "Learn EF Core",
                            TodoListId = 3
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            Description = "Write SELECT and JOIN queries",
                            Name = "Practice SQL",
                            TodoListId = 3
                        },
                        new
                        {
                            Id = 9,
                            Active = false,
                            Name = "Read about LINQ",
                            TodoListId = 3
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            Name = "Clean kitchen",
                            TodoListId = 4
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            Description = "Wash dark clothes",
                            Name = "Do laundry",
                            TodoListId = 4
                        },
                        new
                        {
                            Id = 12,
                            Active = false,
                            Name = "Water plants",
                            TodoListId = 4
                        });
                });

            modelBuilder.Entity("DAL.Entities.TodoList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TodoList");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Grocery list"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Work tasks"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Study plan"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Home chores"
                        });
                });

            modelBuilder.Entity("DAL.Entities.Todo", b =>
                {
                    b.HasOne("DAL.Entities.TodoList", null)
                        .WithMany()
                        .HasForeignKey("TodoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
